### ISSUE TITLE
automation doesn't work

### ISSUE THREAD

**Issue by Palex1974** [opravdin/weback-hass#16]
The abir x8 vacuum cleaner is integrated through this repository, manually controlled from HA. But the automation for starting the vacuum cleaner does not work. The vacuum.start service sees this vacuum cleaner.
![23240295](https://user-images.githubusercontent.com/75608518/123434472-30e50d80-d5d5-11eb-8ae7-0edc066801ea.jpg)
![23240363](https://user-images.githubusercontent.com/75608518/123434494-37738500-d5d5-11eb-913c-af68682b2ef6.jpg)

**Comment by GigaVik** [comment]
Try using the general command - vacuum.send_command
 For example, to start automatic cleaning:
```
- service: vacuum.send_command 
   entity_id: vacuum.xs_x8....
   data:
     command: blablabla
     params: 
       working_status: SmartClean
```
